---
- name: Converge
  hosts: localhost
  gather_facts: no
  vars_files:
    - "vars/{{ lookup('env', 'TEST_OPERATOR_SHORTNAME') }}.yml"
  collections:
    - kubernetes.core

  tasks:
    - import_tasks: kustomize.yml
      vars:
        state: present
