---
- name: Destroy
  hosts: localhost
  gather_facts: false
  vars_files:
    - "vars/{{ lookup('env', 'TEST_OPERATOR_SHORTNAME') }}.yml"
  collections:
    - community.kubernetes

  tasks:
    - import_tasks: kustomize-prepare.yml

    - name: Remove CR samples
      loop: "{{ crds.keys() | list }}"
      when: lookup('k8s', api_version='apiextensions.k8s.io/v1', kind='CustomResourceDefinition', resource_name=crds[item].name)
      k8s:
        state: absent
        namespace: '{{ namespace }}'
        definition: "{{ lookup('template', '/'.join([samples_dir, crds[item].sample_file])) | from_yaml }}"
        wait: true

    - import_tasks: kustomize.yml
      vars:
        state: absent

    - import_tasks: kustomize-prepare.yml
      vars:
        kustomize_prepate_set: false
