---
- name: Verify
  hosts: localhost
  gather_facts: no
  vars_files:
    - "vars/{{ lookup('env', 'TEST_OPERATOR_SHORTNAME') }}.yml"
  collections:
    - community.kubernetes

  vars:
    ctrl_label: control-plane=controller-manager

  tasks:
    - block:
        - name: Include all test files from tasks/
          include_tasks: '{{ item }}'
          loop: "{{ query('fileglob', 'verify_tasks/' + operator_shortname + '/*_test.yml') | sort }}"
      rescue:
        - name: Retrieve relevant resources
          k8s_info:
            api_version: '{{ item.api_version }}'
            kind: '{{ item.kind }}'
            namespace: '{{ namespace }}'
          loop: "{{ verify_debug_resources }}"
          register: debug_resources

        - name: Retrieve Pod logs
          k8s_log:
            name: '{{ item.metadata.name }}'
            namespace: '{{ namespace }}'
            container: manager
          loop: "{{ q('k8s', api_version='v1', kind='Pod', namespace=namespace, label_selector=ctrl_label) }}"
          register: debug_logs

        - name: Output gathered resources
          debug:
            var: debug_resources

        - name: Output gathered logs
          debug:
            var: item.log_lines
          loop: '{{ debug_logs.results }}'

        - name: Re-emit failure
          vars:
            failed_task:
              result: '{{ ansible_failed_result }}'
          fail:
            msg: '{{ failed_task }}'
