---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "../default/vars/{{ lookup('env', 'TEST_OPERATOR_SHORTNAME') }}.yml"
  collections:
    - kubernetes.core

  tasks:
    - name: Destroy test kind cluster
      command: kind delete cluster --name {{ operator_shortname }}-test --kubeconfig {{ kubeconfig }}

    - import_tasks: ../default/kustomize-prepare.yml
      vars:
        kustomize_prepare_set: false
