nameprefix: "{{ lookup('env', 'TEST_OPERATOR_NAMEPREFIX') |
  default(operator_shortname + '-', true) }}"
namespace: "{{ lookup('env', 'TEST_OPERATOR_NAMESPACE') |
  default(operator_shortname + '-test', true) }}"
omit_crds_deletion: "{{ lookup('env', 'TEST_OPERATOR_OMIT_CRDS_DELETION') |
  default(false, true) | bool }}"
verify_debug_resources:
  - api_version: v1
    kind: Pod
  - api_version: apps/v1
    kind: Deployment
  - api_version: v1
    kind: Secret
  - api_version: v1
    kind: ConfigMap

# kustomize
kustomize: "{{ lookup('env', 'KUSTOMIZE_PATH') | default('kustomize', true) }}"
kustomize_edit_set: "{{ 'set' if kustomize_prepare_set | default(true) | bool else 'unset' }}"
kustomize_edit_add: "{{ 'add' if kustomize_prepare_set | default(true) | bool else 'remove' }}"
kustomize_config_dirs:
  - "{{ config_dir }}/testing"


# default
ansible_python_interpreter: '{{ ansible_playbook_python }}'
config_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/config"
samples_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/config/samples"
operator_image: "{{ lookup('env', 'OPERATOR_IMAGE') }}"
operator_pull_policy: "{{ lookup('env', 'OPERATOR_PULL_POLICY') if
  lookup('env', 'OPERATOR_PULL_POLICY') | default(false, true) else
  'Never' if lookup('env', 'MOLECULE_SCENARIO_NAME') == 'kind' else 'Always' }}"

# kind
project_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
operator_image_args:
  COLLECTION_FILE: "{{ lookup('env', 'COLLECTION_FILE') | default('krestomatio-k8s-master.tar.gz', true) }}"
kind_image: kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9
kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
